language: objective-c
osx_image: xcode11.2
before_install:
- nvm install v12.16.2 --reinstall-packages-from=node
- nvm use v12.16.2
- echo rvm_autoupdate_flag=2 >> ~/.rvmrc
- wget http://dl.google.com/android/android-sdk_r24.4.1-macosx.zip
- unzip android-sdk_r24.4.1-macosx.zip
- export ANDROID_HOME=$PWD/android-sdk-macosx
- export ANDROID_SDK_ROOT=$PWD/android-sdk-macosx
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
- echo yes | android update sdk --filter android-28 --no-ui --force > /dev/null
- echo yes | android update sdk --filter build-tools-28.0.3 --all --no-ui --force > /dev/null
- cd app
install:
- npm install -g cordova
script:
- cordova platform add ios@5.1.1
- cordova platform add android

#install:
#  - "build script"

#script:
#  - "test script"

addons:
  browserstack:
    username: "peterkruyen1"
    access_key: 
      secure: "f4H6eoDaJo0X9RcVZOhcvi+H5iVRlW62ioWBPf/I47Cwg7xk8ZaRXd7+zoIc9pSHO69KYvOV1aYeIyDLsbX6x7yuqGRjLt7u42RHek71k2iexHVpn2loEfH8oQIFfu7XbFuWf+CJXXsXHvmhvAjWkLObMEgmhMGzRyBJOMkjH9Jv72j2jrfFjD5pBimmffqH/pPawrzWjJdM85tnTbDe/DJ2ebDM0nJ0LK72W88sn2bboHB9/W3oNi9Ekw0JwQTgb+KvCDURXzVDlhdBN0/EKQTtqXzpC9TudzT+z+H3X3hHVLPkbAcVuSX56qSav+OGi8tKprvctdOpI3j7BUe95Df0Iosb/3jkP3oAwjrmStH0xsifxIayEqBKExAgTFe1TTuGP4dEq3TD641MDa5pUfDbiLZMgvX6dXbj/0q3+4R21wwPKmGSVYzN+H460mnr1HBbnESOI6jtw95BHuQvocOwbTzswj9JAathvuiDd1yz7UIG1cn+U4fMzvzq/Ca8NZ/ruV2R9wKGi8h9dVloHU2lqsi6fk+i8cbTJ9SBQ5n2rHttaOAE1HmyGQG9pN31hLCA7Hs+GYZxI/bwzMIk5rZvTAiVEK1wZEeM+Mli+PLwA5XWWxo6/KxHrrCL1OgtCwagIILrY1YRziFtsQ/bfossExDRd0xQT9JnNmuj7c8="  
      app_path: "dearscholar.apk"